Feature/adds common conftest
f-lab-edu/CatchTable pull request #12
Opened 2023-07-03 09:03 UTC by teeinn

shared parameters가 있는 method를 위한 common conftest.py 작성

2023-07-11 12:16 UTC, f-lab-jorge requested changes
고칠 부분 코멘트 드렸어요.

fixture를 어디에 왜 쓰는지를 한번 찾아보시면 좋을거 같아요!

2023-07-11 12:16 UTC, f-lab-jorge commented on src/tests/e2e/conftest.py
> +    client.post("/owners/", json=owner_ex_json)
이런건 fixture가 아니라 테스트에 그대로 넣으면 될거 같아요. fixture 는 고정된 값 이라고 보시면 되요

2023-07-11 12:16 UTC, f-lab-jorge commented on src/tests/e2e/owner/test_owner_delete_api.py
> +def test_delete_owner_not_existed(client, owner_client_post):
보통 테스트 함수 명에 실패/성공을 적으면 좋아요. 이 테스트는 실패인데 어떤 이유로 실패인지를 함수명만 보고 알 수 있게요

2023-07-11 12:16 UTC, f-lab-jorge commented on src/tests/unit/conftest.py
> +    owner.add_owner(owner_ex, override_get_uow)
이것도 값이 아니라 함수기 때문에 fixture가 아닌 테스트에 직접 들어가면 될거 같아요

2023-07-23 10:23 UTC, teeinn commented on src/tests/e2e/conftest.py
> +    client.post("/owners/", json=owner_ex_json)
넵!!

2023-07-23 10:25 UTC, teeinn commented
> 고칠 부분 코멘트 드렸어요.
> 
> fixture를 어디에 왜 쓰는지를 한번 찾아보시면 좋을거 같아요!

옙! 감사합니다!

2023-07-25 11:47 UTC, f-lab-jorge reviewed
네 이런식으로 테스트코드 짜가면 좋을거 같아요!

네이밍 관련해서 궁금한거만 코멘트 달았어요

2023-07-25 11:47 UTC, f-lab-jorge commented on src/tests/e2e/menu/test_menu_get_api.py
> +def test_get_menu_returns_201(client, owner_ex_json, restaurant_ex_json, menu_ex_json):
ex는 무슨 의미인가요?

2023-07-25 13:20 UTC, merged