[#18] app과 postgre 연동하는 yaml 작성
f-lab-edu/CatchTable pull request #19
Opened 2023-08-22 10:37 UTC by teeinn

minikube에서 두 파드 생성하여 연동하고 access 가능한지 확인

2023-08-22 10:40 UTC, teeinn commented on kubernetes/catchtable.yaml
> +  type: LoadBalancer
일단은 minikube에서 동작하는 pod에 접근을 위해 loadbalancer 타입을 선언했는데 cloud에 올리려면 clusterip로 하고 ingress, ingress controller 까지 구성해야 할까요?

2023-08-22 11:31 UTC, f-lab-jorge requested changes
수정해야할 부분 코멘트 드렸습니다!
근데 미니쿠베에 인그레스가 되나요?

2023-08-22 11:31 UTC, f-lab-jorge commented on .github/workflows/docker-image.yml
> +on: [pull_request]
마스터에 머지할때만  이미지를 푸시하면 될거 같아요

2023-08-22 11:31 UTC, f-lab-jorge commented on kubernetes/catchtable-secret.yaml
> +  URL : cG9zdGdyZXNxbDovL215dXNlcjpteXBhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9teWRi
시크릿은 보통 깃헙 레포에 노출되면 안돼요. 위에 값이 암호화된게 아니라 그냥 base64 인코딩이라 바로 해킹이 가능해요.
시크릿은 클러스터에 직접 배포하거나 cd 툴을 이용해 배포해요

2023-08-22 11:31 UTC, f-lab-jorge commented on kubernetes/postgres-secret.yaml
> +  POSTGRES_USER: bXl1c2Vy
이 시크릿도 마찬가지

2023-08-22 11:31 UTC, f-lab-jorge commented on kubernetes/postgres.yaml
> +kind: Deployment
db같은 경우는 deployment보다는 statefulset을 이용하는게 좋습니다

2023-08-22 11:31 UTC, f-lab-jorge commented on src/app/config.py
>  def get_postgres_uri():
fastapi의 Setting 관련한 것을 사용하는게 좋아요
https://fastapi.tiangolo.com/advanced/settings/?h=setting#pydantic-settings

2023-08-25 12:54 UTC, teeinn commented on .github/workflows/ci_cd.yml
> +      - feature/kubernetes_yaml
일단 test 중이라 master는 기재하지 않았습니다!

2023-08-25 13:00 UTC, teeinn commented on .github/workflows/ci_cd.yml
> +
아직 tag를 달지 않았는데, tag가 달릴경우 release를 위한 workflow 파일은 따로 구성을 해야할까요?

2023-08-25 13:02 UTC, teeinn commented on k8s/catchtable-ingress.yaml
> +  namespace: development
namespace를 development로 설정했는데, release를 할 경우 똑같은 yaml 파일들을 따로 구성해야 할까요?

2023-08-25 13:04 UTC, teeinn commented on k8s/kustomization.tmpl.yaml
> +
이런식으로 resource 그룹을 묶으면 될까요?

2023-08-25 13:06 UTC, teeinn commented on k8s/kustomization.tmpl.yaml
> +  newTag: ${IMAGE_TAG}
업데이트 된 이미지를 이 파일에서 이렇게 구성하면 deployment에도 자동으로 업데이트 될까요?

2023-08-25 13:07 UTC, teeinn commented on kubernetes/postgres.yaml
> +kind: Deployment
in progress

2023-08-27 14:34 UTC, f-lab-jorge reviewed
잘 구성하셨습니다!

한가지 개선해볼점은 지금 kustomize를 사용하는데 
kustomize를 왜 쓰는지 알면 좋을거 같아요.

그 후에 base, dev, prod로 나눠서 구성하면 완벽할듯 해요

2023-08-27 14:34 UTC, f-lab-jorge commented on .github/workflows/ci_cd.yml
> +
불필요한 new line이 많은거 같아요. 깔끔하게 정리하면 보기 좋을거 같네요

2023-08-27 14:34 UTC, f-lab-jorge commented on .github/workflows/ci_cd.yml
> +
어떤 tag 말씀하시는거예요?

2023-08-27 14:34 UTC, f-lab-jorge commented on k8s/catchtable-ingress.yaml
> +  namespace: development
kustomize 사용하니 base를 두고 dev, prod 디렉토리 따로 만들어서 patch 하면 될거 같아요

2023-08-27 14:34 UTC, f-lab-jorge commented on k8s/kustomization.tmpl.yaml
> +
넵 좋습니다!

2023-08-27 14:34 UTC, f-lab-jorge commented on k8s/kustomization.tmpl.yaml
> +  newTag: ${IMAGE_TAG}
kubectl apply -k 를 실행할떄 위에 변수들을 넣어주면 되요

2023-08-31 10:44 UTC, teeinn commented on docker-compose.yml
>      tty: true
config 수정에 따른 yaml 파일 수정

2023-08-31 10:45 UTC, teeinn commented on src/app/config.py
>  def get_postgres_uri():
config를 수정하였습니다.

2023-08-31 11:02 UTC, teeinn commented
> 잘 구성하셨습니다!
> 
> 한가지 개선해볼점은 지금 kustomize를 사용하는데 kustomize를 왜 쓰는지 알면 좋을거 같아요.
> 
> 그 후에 base, dev, prod로 나눠서 구성하면 완벽할듯 해요

Kustomize는 쿠버네티스를 위한 구성 관리 도구로, 선언적인 설정 파일을 사용하여 배포, 서비스 및 기타 쿠버네티스 객체를 사용자 정의하고 관리할 수 있는 기능을 제공합니다. 이를 통해 쿠버네티스 응용 프로그램의 다른 버전을 중복된 YAML 매니페스트를 생성하거나 동일한 배포의 복사본을 여러 개 생성하지 않고도 생성할 수 있습니다.

Kustomize를 사용하면 쿠버네티스 응용 프로그램에 대한 기본 구성을 정의하고, 다른 환경이나 사용 사례에 대한 다양한 오버레이로 사용자 정의할 수 있습니다. Kustomize는 패치(patch)를 사용하여 기본 구성을 수정하고 변경 사항을 적용하여 사용자 지정된 응용 프로그램 버전을 생성합니다.

Kustomize는 쿠버네티스 구성을 유연하고 효율적으로 관리하며, 구성 파일의 중복을 줄이는 방법을 제공하여 다양한 환경에서 쿠버네티스 응용 프로그램을 유지 관리하고 관리하기 쉽게 만듭니다.

2023-09-06 11:46 UTC, merged