end2end_test_for_crud
f-lab-edu/CatchTable pull request #9
Opened 2023-06-11 15:02 UTC by teeinn

**06/12 Commit**

모든 domain에 대한 end to end test 작성

2023-06-11 15:15 UTC, teeinn commented
![Screenshot from 2023-06-12 00-14-42](https://github.com/f-lab-edu/CatchTable/assets/45514456/6b3f1902-a5f6-42c4-a1d0-fe7cc166a509)

2023-06-12 14:21 UTC, f-lab-jorge requested changes
네 좋습니다!

테스트 방식만 코멘트 드렸는데 한가지 고치면 좋을거 같아요

2023-06-13 01:23 UTC, teeinn commented on src/app/test/e2e/menu/test_menu_get_api.py
> +def test_get_menu_returns_201(client, owner_id, restaurant_id, owner_ex, restaurant_ex, menu_ex):
넵!! 수정해 보도록 하겠습니다!

2023-06-25 11:46 UTC, f-lab-jorge commented
pr 실패하는거만 봐주세요!

2023-06-25 12:20 UTC, teeinn commented on src/tests/e2e/owner/conftest.py
> +    client.post("/owners/", json=owner_ex_json)
owner post 하는 부분을 fixture로 만들고,
test 시에 파라미터에서 부르는데 이렇게 하는게 맞나요?

2023-06-26 07:50 UTC, merged